-- CreateEnum
CREATE TYPE "CategoryType" AS ENUM ('ELECTRONICS', 'MOBILE', 'LAPTOP', 'TABLET', 'CAMERA', 'ACCESSORIES', 'SMARTWATCH', 'TV', 'AUDIO', 'HOME_APPLIANCES', 'KITCHEN', 'FURNITURE', 'CLOTHING', 'MEN_CLOTHING', 'WOMEN_CLOTHING', 'KIDS_CLOTHING', 'SHOES', 'BAGS', 'TOYS', 'SPORTS', 'FITNESS', 'HEALTH', 'BEAUTY', 'BOOKS', 'STATIONERY', 'PET_SUPPLIES', 'GROCERY', 'JEWELRY', 'OTHER');

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "category" "CategoryType";
